# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Talking to the Duck
email: chris.zeeb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Talking to the Duck: I sure hope he understands what I'm saying.  I sure don't.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.talkingtotheduck.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  czeeb

# Build settings
markdown: kramdown

# Outputting
permalink: pretty
